name: Trigger Label Pipeline

on:
  pull_request:
    types: [labeled]

jobs:
  trigger_on_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for the trigger label
        id: check_label
        run: |
          echo "Checking labels for trigger..."
          labels=$(echo '${{ toJSON(github.event.pull_request.labels) }}' | jq -r '.[].name')
          echo "Labels: $labels"
          
          if echo "$labels" | grep -q "release-build"; then
            echo "Trigger label found."
          else
            echo "No trigger label found. Exiting."
            exit 1
          fi

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build debug AAB
        if: success()
        run: |
          echo "Building the debug Android App Bundle..."
          ./gradlew bundleRelease

      - name: Upload debug AAB artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: debug-aab
          path: app/build/outputs/bundle/debug/app-debug.aab
